import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'

const Home: NextPage = () => {
  const [message, setMessage] = useState('');
  const [submitting, setSubmitting] = useState(false);

  const handleSubmit = async (event: React.FormEvent) => {
    event.preventDefault();
    setSubmitting(true);

    // Simulated API call
    setTimeout(() => {
      alert(`Feedback submitted: ${message}`);
      setMessage('');
      setSubmitting(false);
    }, 1000);
  };

  return (
    <div>
      <Head>
        <title>Feedback Trees</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>
          Welcome to Feedback Trees
        </h1>

        <p>
          Have feedback? We’d love to hear it, but please don’t share sensitive information.
        </p>

        <form onSubmit={handleSubmit}>
          <textarea
            value={message}
            onChange={(e) => setMessage(e.target.value)}
            disabled={submitting}
          />
          <button type="submit" disabled={submitting}>
            {submitting ? 'Submitting...' : 'Submit Feedback'}
          </button>
        </form>

        <Link href="/about">
          <a>About Us</a>
        </Link>
      </main>

      <footer>
        <span>Powered by </span>
        <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
      </footer>
    </div>
  )
}

export default Home